Rechnerpraktikum/wienerfestwochen/urls.py
from django.urls  import path, include
from .            import views


app_name = 'wienerfestwochen'

urlpatterns = [
    path('dialog1/', views.dialog1, name='dialog1'),
    path('', views.index, name="index"),
    path('Produktion/', views.Produktion_view, name="Produktion"),
]

Rechnerpraktikum/wienerfestwochen/models.py
from django.db import models
from django.utils import timezone





class Produktion(models.Model):
    Produktionid = models.IntegerField(max_length=30, blank=False, unique=True, verbose_name='Produktion')
    Titel = models.IntegerField(max_length=30, blank=False, verbose_name= "Titel")
    Leitung = models.CharField(max_length=30, blank=False, verbose_name= 'Leitung')

class Person(models.Model):
    PID = models.IntegerField(max_length=30, blank=False, unique=True)
    PName = models.CharField(max_length=30, blank=False)

    ist_extern = models.BooleanField(max_length=2, blank=False,
                           choices=[('JA', 'JA'), ('Nein', 'Nein'), ])

    def __str__(self):
        return self.Pname

class Team(models.Model):
    Teamid = models.IntegerField(max_length=4, blank=False, unique=True, verbose_name='Teamid')
    FS_PR = models.ForeignKey(Produktion, on_delete=models.PROTECT, blank=False)

class Teammitglied(models.Model):
    TMID = models.IntegerField(max_length=30, blank=False, unique=True, verbose_name='id')
    Fachbereich = models.CharField(max_length=30, blank=False)
    Stundenlohn = models.IntegerField(max_length=30, blank=True, verbose_name='Stundenlohn')
    FS_TID = models.ForeignKey(Team, on_delete=models.PROTECT, blank=False)
    FS_PID = models.ForeignKey(Person, on_delete=models.PROTECT, blank=False)
    def __str__(self):
        return self.Fachbereich + " " + self.Stundenlohn


class Auftritt(models.Model):
    FS_TID = models.ForeignKey(Team, on_delete=models.PROTECT, blank=False, verbose_name='Auftritt')
    AuftrittID = models.IntegerField(max_length=30, blank=False, unique=True)
    Zeit = models.DateTimeField(default=timezone.now(), blank=False)

    def __str__(self):
        return




Rechnerpraktikum/wienerfestwochen/forms.py
from django import forms
from .models import Team, Person, Teammitglied, Produktion



class ProduktionForm(forms.ModelForm):
	class Meta:
		model = Produktion
		fields = ('id', 'Titel', 'Typ', 'Dauer', 'Leitung', 'Sprache', 'hat_Untertitel')


class TeamForm(forms.ModelForm):
	class Meta:
		model = Team
		fields = ('id', 'FS_ProduktionID')


class PersonForm(forms.ModelForm):
	class Meta:
		model = Person
		fields = ('id', 'PName', 'ist_extern')


class TeammitgliedForm(forms.ModelForm):
	class Meta:
		model = Teammitglied
		fields = ('id', 'Fachbereich', 'Stundenlohn', 'FS_TeamID', 'FS_PersonID')

Rechnerpraktikum/wienerfestwochen/views.py
from django.shortcuts import render
from .models import Produktion, Team, Person, Teammitglied
from .forms import ProduktionForm, TeamForm, PersonForm, TeammitgliedForm


def dialog1(request):
		return render(request, "dialog1.html", {})

def index(request):
    return render(request, 'wienerfestwochen/base.html')

def Produktion_view(request):
	if request.method == 'POST':
		form = ProduktionForm(request.POST)
		if form.is_valid():
			form.save()
			form = ProduktionForm()
			prods = Produktion.objects.filter().order_by('Titel')
	else:
		prods = Produktion.objects.filter().order_by('Titel')
		form = ProduktionForm()
	args = {}
	args['form'] = form
	args['prods'] = prods
	return render(request, 'wienerfestwochen/Produktion.html', args)

Rechnerpraktikum/wienerfestwochen/templates/dialog1.html
Das ist der Dialog 1 mit allen seinen Daten und Funktionen.

Rechnerpraktikum/wienerfestwochen/templates/wienerfestwochen/Produktion.html
{% extends 'wienerfestwochen/base.html' %}

<!-- Kurzanleitung für crispy forms:
  https://simpleisbetterthancomplex.com/tutorial/2018/08/13/how-to-use-bootstrap-4-forms-with-django.html
-->

{% load crispy_forms_tags %}


{% block title %}
    Produktionen verwalten
{% endblock %}


{% block Formular-Überschrift %}
    <h1 align = "center">Produktionen verwalten</h1>
{% endblock %}


{% block Seiten-Inhalt %}
	<p>Das ist jetzt mal ein Erfassungsformular für eine neue Produktion (Einfügen, Ansehen)!</p>

	<p>
	<form action="/Produktion/" method="POST">
    <div class="form-group">
		{% csrf_token %}
		{{ form|crispy }}
		<input type="submit" value="Neue Produktion abspeichern" / >
    </div>
	</form>
	</p>

	<table border="2">

		<tr>
			<th>ID</th>
			<th>Titel</th>
			<th>Typ</th>
			<th>Dauer</th>
      <th>Leitung</th>
      <th>Sprache</th>
      <th>hat_Untertitel</th>
		</tr>

		{% for Produktion in prods %}
			<tr>
				<td align="right"> {{Produktion.id}}</td>
				<td align="left">  {{Produktion.Titel}}</td>
				<td align="center">{{Produktion.Typ}}</td>
				<td align="Right"> {{Produktion.Dauer}}</td>
        <td align="Left"> {{Produktion.Leitung}}</td>
        <td align="Center"> {{Produktion.Sprache}}</td>
        <td align="right"> {{Produktion.hat_Untertitel}}</td>
			</tr>
		{% endfor %}

	<table>

	<p>Das wird dann später mein Produktion-Datenverwaltungsformular (ist noch um Ändern und Löschen zu erweitern)!</p>

{% endblock %}

Rechnerpraktikum/wienerfestwochen/templates/wienerfestwochen/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Wiener Festwochen Verwaltungstool Hauptmenü
        {% endblock %}
    </title>
</head>


<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  	<span class="navbar-toggler-icon"></span>
    </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Verwaltung
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'wienerfestwochen:Produktion' %}">Produktionen</a>
              </div>
            </li>
          </ul>
          {% if user.is_authenticated %}
          <ul class="navbar-nav ml-auto">
            <li>Hallo, {{request.user.username}}!</li>
          </ul>
          {% endif %}
      </nav>
<!--
  --<center> -->
<div class="container">
    {% block Formular-Überschrift %}
		<h1 align = "center">WF-Administration - Home</h1>
	{% endblock %}

    {% block Seiten-Inhalt %}

        {% block Formular-Inhalt %}

        <ul class="list-group">
          <li class="list-group-item"><a href="{% url 'wienerfestwochen:Produktion' %}">Produktionen verwalten</a></li>
          <li class="list-group-item">Dapibus ac facilisis in</li>
          <li class="list-group-item">Morbi leo risus</li>
          <li class="list-group-item">Porta ac consectetur ac</li>
        </ul>
        {% endblock %}

    {% endblock %}

<!--
--</center> -->
</div>
</body>

</html>